### ISSUE TITLE
Support for safari in Mac osx 10.14 beta (Mojave)

### ISSUE THREAD

**Issue by riverful** [guyht/vimari#107]
Hi devs,

I'm just wondering Vimari will be uploaded into official safari gallery so that we can use it even in the Mojave safari. Love to use it and hope to use it in safari even in Mojave, but safari replies that only authorized extension in official gallery is allowed to be used. Would you please let us know about upload plan? If the plan exists, can you please update the approximate schedule?

**Comment by simeg** [comment]
Hi, see #103.

**Comment by riverful** [comment]
Thanks for the update, that's what I expected.
