### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by northleafup** [guyht/vimari#119]
### Version

- [ ] Version 1
- [ x ] Version 2

### My Problem

I don't edit anything. When I open the project by xcode, i can not compile it . The error like this:
<img width="720" alt="image" src="https://user-images.githubusercontent.com/15024762/45800503-ac5a5780-bce3-11e8-94ba-745328f211d4.png">

How can I build it successfully? 
Thanks.

**Comment by fnurl** [comment]
@northleafup I had the same problem yesterday, try the solution mentioned in [this comment](
https://github.com/guyht/vimari/issues/103#issuecomment-422737243).

**Comment by northleafup** [comment]
@fnurl 
Thanks for your help. By this comment, I have build success .
