### ISSUE TITLE
can not close tab 

### ISSUE THREAD

**Issue by northleafup** [guyht/vimari#122]
### Version

- [ ] Version 1
- [x] Version 2

### My Problem

I install it ok , but I can not close tab ,for example : https://mbd.baidu.com/newspage/data/landingsuper?context=%7B%22nid%22%3A%22news_9734535082817825016%22%7D&n_type=1&p_from=3

**Comment by simeg** [comment]
With the new Safari Extension API there's no way to close the current tab you have open. See [this comment](https://github.com/guyht/vimari/issues/103#issuecomment-407108149) for more context.
