### ISSUE TITLE
Can't compile vimari 2.0 for Safari 12

### ISSUE THREAD

**Issue by FreddieOliveira** [guyht/vimari#123]
When building vimari 2.0 for Safari 12 on macOS High Sierra, xcode keeps complaining about signing, as shown in the picture above.

![xcode1](https://user-images.githubusercontent.com/9597536/46112144-e635cd00-c1bf-11e8-8f82-432338034bb2.png)

I tried to log in with my Apple ID and change the team to my account, but the error persists, as shown above

![xcode2](https://user-images.githubusercontent.com/9597536/46112151-f188f880-c1bf-11e8-8317-86f992358516.png)

I don't have a development team ID, so I can't change it in project.pbxproj file properties. 

![xcode3](https://user-images.githubusercontent.com/9597536/46112238-5e9c8e00-c1c0-11e8-8b1a-ebe619db2e32.png)

**Comment by CarlosEvo** [comment]
You need to sign both `vimari` and `extension`
![image](https://user-images.githubusercontent.com/11689106/46113101-e4f5a780-c1a1-11e8-8d8a-3514c7287a04.png)

**Comment by FreddieOliveira** [comment]
Ooh, I missed that. It works perfectly now. Thanks!

**Comment by apparition47** [comment]
Probably would be even better if this app extension was published on the Mac App Store if the original author has Apple Dev membership.

**Comment by simeg** [comment]
Thanks @CarlosEvo! I've added more info to the installation instructions (https://github.com/guyht/vimari/commit/3538260637449677b1d3dc6dfecca1a3f46a7d07).

@apparition47 Yes, that is the plan. But first I'd like to figure out how to do Settings, otherwise everyone will have to use the same settings.
