### ISSUE TITLE
Document Differences between sVim

### ISSUE THREAD

**Issue by bhagyas** [guyht/vimari#124]
Would like to see a comparison between vimari and sVim on README.

**Comment by simeg** [comment]
Hi @bhagyas.

If you want to do a comparison you are welcome to do so, but if you're asking for someone else to do it I don't think you'll have any luck. It's a very specific request and I think you can quickly get an overview of what the two extensions can do by looking at the documentation.

Right now it looks like [sVim](https://github.com/flipxfx/sVim) only supports Safari v11 and below which I guess is a big difference.
