### ISSUE TITLE
Not all hot keys appear to work

### ISSUE THREAD

**Issue by sdondley** [guyht/vimari#126]
### Version

- [ ] Version 1
- [x ] Version 2

I got the extension installed on Mojave. Many hotkeys don't do anything:

F (f works fine)
w
q
x
X

**Comment by simeg** [comment]
Hi @sdondley.

Apple limited the API for their new extensions, see [this comment](https://github.com/guyht/vimari/issues/103#issuecomment-407108149) for more info.

For new releases you have to check back on the repo, in the future you'll be notified via the App Store though.

**Comment by sdondley** [comment]
If I update the github repo, do I have to go back through the install process with xcode or can i just restart the browser?

**Comment by simeg** [comment]
The current installation process is temporary until I can figure out how to get the extension on to App Store, but yes you'd probably have to redo most of the process.

**Comment by sdondley** [comment]
OK, thanks for getting back. I'll try back in a couple of months.
