### ISSUE TITLE
vimari for safari 12 not compatible with macos Sierra

### ISSUE THREAD

**Issue by BakerChan** [guyht/vimari#129]
### Version

- [ ] Version 1
- [x ] Version 2

**Comment by simeg** [comment]
Hi @BakerChan.

You might have to use version 1, please try that and let me know how it went.

**Comment by simeg** [comment]
I guess if you're on Safari 12 you can't use version 1 - my bad. I can't really give support for such an old OS version. I have no way of testing it my self so my only advice would be to look through old issues and see if you can find something.

Sorry for not being able to help more.
