### ISSUE TITLE
Safari freezing for 1-2 minutes on pages with many links

### ISSUE THREAD

**Issue by Jayphen** [guyht/vimari#55]
It took a while to figure out what the issue was (I thought it was Safari itself at first), but I have narrowed it down to Vimari.

This happens most often when I browse forum topics with many threads (possibly because there are hundreds of links on the page at once).

I am using Safari 8.0.5

**Comment by simeg** [comment]
Performance could maybe be improved, I'm not familiar enough with the codebase to be the judge of that. But since you're the only one having this problem I won't spend any time on fixing it now. Feel free to look into it on your own.
