### ISSUE TITLE
how to search?

### ISSUE THREAD

**Issue by ghost** [guyht/vimari#61]

**Comment by hanyimin** [comment]
hi：
  in vim ,i can search by input "/",but how can i search in safari?

**Comment by gjcourt** [comment]
Just installed this plugin and I have to say that I'm very impressed, very nicely done. After opening the plugin I did notice 2 small things.

1. Defaulting the `CTRL` prefix might be a little frustrating to people coming from vimiim, it took me 5 minutes to figure out that this plugin wasn't broken. This would probably drastically improve adoption, but that's only a hunch
2. Not being able to type `/` and search in the page, and then use the vim-style `n` and `shift-n` navigation is very limiting.

Other than these 2 minor issues, keep up the good work.

**Comment by simeg** [comment]
Duplicate, see #60.
