### ISSUE TITLE
'no command prefix' - prevent javascript autofocus on Google

### ISSUE THREAD

**Issue by johnathanz** [guyht/vimari#63]
Is there a way to prevent the javascript autofocus from loading on Google.

I'd like to use vimari without having to use press a 'command prefix' similar to how Vimium functions in Chrome.  Unfortunately, sites like Google forces the cursor into the search box, which means commands issued for vimari ends up on the search box (actually the first keypress works, then all subsequent key presses end up in the search box).

A search engine like 'DuckDuckDuck' doesn't have this problem. 

Any chance this could be enabled in vimari?

Thanks!

**Comment by simeg** [comment]
Duplicate, see #38.
