### ISSUE TITLE
Does not work together w/ Gmail

### ISSUE THREAD

**Issue by normenmueller** [guyht/vimari#65]
Hi, I have added `https://gmail.com, https://mail.google.com, https://mail.google.com/mail/` to "Excluded URLs", disabled vimari, enabled vimari but still, e.g., selecting a message and hitting `l` for labelling does not work. Any suggestions?

**Comment by anshukla** [comment]
+1; current workaround is to add a command prefix.

**Comment by connor** [comment]
The excluded URLS are `comma separated`, so your syntax for excluding them is incorrect.

Remove the extra space after each comma, and make it like so:

`https://gmail.com,https://mail.google.com,https://mail.google.com/mail`

I just did that and it works great for me.

**Comment by anshukla** [comment]
Good catch -- that worked for me.

**Comment by erichurst** [comment]
I was able to regain Gmail's keyboard shortcuts with the follow exclusions `https://gmail.com*,https://mail.google.com*,https://mail.google.com/mail/*/**`. Perhaps overkill.
