### ISSUE TITLE
Vimari doesn't handle pages that steal focus on load (e.g. google.com)

### ISSUE THREAD

**Issue by mtchllbrrn** [guyht/vimari#71]
Some pages steal focus upon load. For instance, google.com will autofocus the search bar. Vimari doesn't handle this behavior very well.

Vimium includes an advanced option called "Don't let pages steal focus on load."  Rolling this feature into Vimari would solve the issue.

**Comment by ChopSu3y** [comment]
yes, i use google a lot and it's very frustrating that I have to use my mouse which defeats the whole purpose of this wonderful extension. Please fix it!

**Comment by simeg** [comment]
I usually just press `Esc` to un-focus input fields, no need to use the mouse.

**Comment by simeg** [comment]
Duplicate, see #38.
