### ISSUE TITLE
Does not work on El Capitan

### ISSUE THREAD

**Issue by herrbischoff** [guyht/vimari#72]
This plugin does not work at all on OS X 10.11 and cannot even be installed. It just does not show up in the extensions list and thus won-t be loaded.

**Comment by elmart** [comment]
Maybe you've misunderstood something about installation?
I've just installed on El Capitan, and it's working fine for me.
Just click on the download link https://github.com/guyht/vimari/releases/latest, and click on the safari extension package to install it.

**Comment by herrbischoff** [comment]
Not at all. Since installing Safari Extensions is as straightforward as it could be, that's what I did. When I get the chance, I'm going to check the system logs during installation and post them here.

**Comment by lavventura** [comment]
Weird, it works for me without any problems.

**Comment by herrbischoff** [comment]
Today I tried it again and — lo and behold — it worked. In the meantime I have found a better suited (for me at least) alternative though: [sVim](https://github.com/flipxfx/sVim)

**Comment by dylan-chong** [comment]
Was it because you have to restart safari once you install or change any settings?

(Sorry to comment on a closed ticket but this might be helpful information)

**Comment by herrbischoff** [comment]
@dylan-chong: Sorry, I cannot remember. I may have rebooted the system from one day to the other although that seems unlikely as I don't do that most days. Also, I have switched to Chrome for its (in my view) superior plugin architecture.
