### ISSUE TITLE
Doesn't work.. at all.

### ISSUE THREAD

**Issue by LexGear** [guyht/vimari#74]
I've been trying to use this for 4 months now. Doesn't seem to work at all.

**Comment by net** [comment]
Works fine for me in the latest version of Safari (9.0.1) in El Capitan (10.11.1). You have to hold ctrl as a modifier key, unless you change that in the extension's settings.

**Comment by posva** [comment]
@LexGear Are you pressing control while using shortcuts?

**Comment by betoharres** [comment]
Me too, I download and try to install clicking in trust and nothing happens o.O
I was using just fine few months ago. 

I update my entire machine weekly

**Comment by yebokang** [comment]
Go to Extensions of Safari Preferences, delete "ctrl" in command prefix and it will work

**Comment by betoharres** [comment]
@yebokang it doesn't even show in the extensions list

**Comment by robooo** [comment]
Same on safari 10.1, tried older versions but always after click on `Trust` button nothing happens

**Comment by nthhisst** [comment]
Working for me on Safari 10.1.1. @robooo is it not showing in the extensions in Safari or is it just not responding to input?

**Comment by robooo** [comment]
@nthhisst not in menu and not responding too, but I think it doesn't get installed

**Comment by simeg** [comment]
What could be confusing is that there's a default modifier key set (ctrl). The extension required it to be held down for any action. This has been removed and will not be included in the upcoming versions, so hopefully people will feel like it works from now on.
