### ISSUE TITLE
`g g` top of page command doesn't trigger

### ISSUE THREAD

**Issue by dylan-chong** [guyht/vimari#80]
The `shift+g` command works, but not `g g`

**Comment by goooooouwa** [comment]
I had the same issue, the workaround I had is to set the shortcut to only `g`, instead of `gg`. Hope it helps.

**Comment by hacker112** [comment]
If `ctrl` is the trigger key. then `ctrl+g g` is the trigger and not `ctrl+g ctrl+g`. Changing the field (Go to the top of the page) to `g ctrl+g` to trigger it with `ctrl+g ctrl+g`.

**Comment by dylan-chong** [comment]
@hacker112  `g ctrl+g` does not work for me

**Comment by simeg** [comment]
I think this problem should be fixed with [version 1.13](https://github.com/guyht/vimari/releases/tag/v1.13) where there is no default modifier key.
