### ISSUE TITLE
Can't press Youtube full screen button with vimari

### ISSUE THREAD

**Issue by dylan-chong** [guyht/vimari#81]
The full screen button is clicked, but youtube shows a popup 
<img width="253" alt="screen shot 2016-08-14 at 10 49 05 am" src="https://cloud.githubusercontent.com/assets/17482349/17646040/bfd56702-620c-11e6-9579-96190143d087.png">

**Comment by kenthinson** [comment]
works fine for me. do you have javascript disabled? are you using the flash or html5 version of youtube?

**Comment by dylan-chong** [comment]
interesting. Something seems to have changed in the last year. Also i seem to be able to just press 'f' as youtube's shortcut.
