### ISSUE TITLE
Link Hint Toggle (open in new tab) doesn't work in macOS 10.12

### ISSUE THREAD

**Issue by lonelytb** [guyht/vimari#82]
It opens the link in the current tab.

**Comment by dongdongdu** [comment]
Same here, just want to open a issue with (open in new tab)~

**Comment by lachlancotter** [comment]
I have this issue on OS X 10.10.5 and Safari Version 10.0 (10602.1.50.0.10). It it was working great until a few days ago. I think the latest Safari release broke it.

**Comment by johnathanz** [comment]
I have this issue too. OSX 10.11.16 (El Capitan), Safari Version 10.0.1 (11602.2.14.0.7)

**Comment by zilman** [comment]
I almost convinced myself I won't miss Vimperator/Firefox with Vimari but this issue is driving me bonkers. Any idea why this started?

**Comment by ChrisLTD** [comment]
I've gone ahead and switched to http://gggritso.com/Vimmy.safariextension/ as an alternative in the interim.

**Comment by shaunpatel** [comment]
Same issue here.

**Comment by nickenchev** [comment]
Not working for me as well.

**Comment by zxdposter** [comment]
Me Too>>>>

**Comment by runartrollet** [comment]
any progress on this?

**Comment by zakkoltun** [comment]
Having the same issue as well.

**Comment by gabrielarpino** [comment]
Same issue for me too

**Comment by swordencao** [comment]
Same issue here

**Comment by guyht** [comment]
Is anyone interested in proposing a fix for this?

**Comment by simeg** [comment]
Confirmed bug, will try to fix until next version.

**Comment by simeg** [comment]
Found and fixed the bug. Fix will be included in version 1.13.0.

**Comment by martinbohman** [comment]
1.13.0 when? 😃

**Comment by simeg** [comment]
@martinbohman We're having some issues around the Apple developer certificates. The version is ready to be released but we need someone to be able to compile it, and that requires a certificate.

If anyone wants to help this project and has a valid Apple developer certificate, let me know.

**Comment by czhu** [comment]
the link hinting still doesn't work? Vimari 1.12 with Safari 11.1.2 on macOS 10.13.6. 
I find the link hinting is the most useful feature of Vimium on Chrome. Would be really nice to fix it. Thanks!

**Comment by simeg** [comment]
@czhu Hi, there's no time being spent on version 1.xx, instead all focus right now is on version 2.00. See the progress + context in #103.

**Comment by czhu** [comment]
@simeg that's the right direction. Can I use the 2.00 on Safari 11.1.2? 
I downloaded the 2.00 version and installed the pre-compiled extension inside, which appears to be 1.12 still. I see a instruction for installing the 2.00 on Safari 12. But I don't want to upgrade my OS yet. Thanks!

**Comment by simeg** [comment]
@czhu I'm not sure if it works on Safari versions below 12, but please try the instructions for installing on Safari 12 and let me know if it works.

**Comment by czhu** [comment]
@simeg seems to work so far on Safari 11.1.2. Happy! Thanks!

I cannot seem to change settings though: 
![image](https://user-images.githubusercontent.com/1476422/43430689-064c833c-941f-11e8-80df-a581fe487732.png)

**Comment by simeg** [comment]
@czhu I'm glad to hear it's working :) Settings are not yet implemented. Please keep an eye on that issue and keep all things related to version 2 in that issue, thanks!
