### ISSUE TITLE
Can't get this to work in Safari Technology Preview Release 45

### ISSUE THREAD

**Issue by cristeahub** [guyht/vimari#95]
Hi!

I can't get this plugin to work in the Safari Technology Preview, it looks like it's installed correctly in the extensions.

<img width="284" alt="image" src="https://user-images.githubusercontent.com/1488921/34049628-6d262028-e1b8-11e7-93b8-9ddb615ebaf8.png">

**Comment by simeg** [comment]
Hi,

I don't know how to help because I don't have any information. What have you tried? How do you know it's not working? Any info would be useful.

**Comment by cristeahub** [comment]
Yeah, sorry about that.

I have installed the v1.12 release here https://github.com/guyht/vimari/releases/tag/v1.12 . And I can see in my extensions gallery that it's installed and checked off. All the settings seem to be working, i.e. I can change them and the changes are remembered.

The logs when I open Safari Technology Preview also prints "vimari" somewhere in them, but I'm not too familiar with the logs.

When I'm on any web page none of the hotkeys are working. Nothing is happening if I press any of them, only keybindings that's native to the site (like GitHub) works. Seems like the extension isn't loaded correctly or something similar.

If there's any way I can get some debug information please tell me and I'll post it here.

**Comment by cristeahub** [comment]
I can't see any HTML injected into any sites either.

**Comment by simeg** [comment]
I just tested with the Safari Technology Preview and it works for me. Does it work in the normal Safari version for you?

One thing that is confusing with version 12 (and that has been changed in the upcoming version) is that you have to hold down the command prefix to make any function work. So by default you have to press `Ctrl + f` to display all the links.

Read the documentation carefully one more time, and if it still doesn't work then try re-install the extension and try `Ctrl + f` again.

**Comment by cristeahub** [comment]
I managed to get this working by reinstalling the Safari Technology Preview and readding the extension. Not sure what caused the issue, but it's working now. Thanks for the help :)
