### ISSUE TITLE
macOS 12 beta do not allow unsafe plugin

### ISSUE THREAD

**Issue by LeonardCohen** [guyht/vimari#99]
could you add it to app store or safari extension gallery?  Much thanks.

**Comment by simeg** [comment]
To do that it needs to be compiled, and to do that a certificate is required - something that neither of us working on this plugin has, unfortunately. See the README for more information.

**Comment by danielcompton** [comment]
Also, the Safari Extension Gallery is deprecated: https://developer.apple.com/documentation/safariextensions
https://developer.apple.com/library/archive/documentation/Tools/Conceptual/SafariExtensionGuide/Introduction/Introduction.html

> Safari extensions refers to the legacy .safariextz-style Safari extensions. Developer-signed Safari extensions are not supported in Safari 12. Safari extensions distributed in the Safari Extension Gallery are deprecated, and Safari 12 is the last release to support them. New submissions to the Safari Extensions Gallery will be accepted until the end of 2018.

**Comment by simeg** [comment]
Hi @jad. Your e-mail was flagged as spam so I didn't get a notification for it, but I just sent you a reply. Let's keep talking via e-mail!

**Comment by simeg** [comment]
Please read the latest in the other issue: #100

**Comment by guyht** [comment]
Hi All - sorry, I only check this periodically, but fully support this - I no longer develop code, but if there is anything I can do to help please let me know.
